<?php

header('Cache-Control: post-check=0, pre-check=0');
header('Pragma: no-cache');
require_once(dirname(__FILE__)."/../include/common.inc.php");
require_once(DEDEINC."/filter.inc.php");

session_start();
if($_SESSION["Zend_Auth"]['storage']->nickname) { 
 
 	         echo "document.write('<dd><a href=\"http://passport.we54.com/Index/logout?forward=".$_GET['forward']."\" style=\" color:#0035a0;\">退出</a><a href=\"http://bbs.we54.com/memcp.php\" target=\"_blank\" style=\" color:#0035a0;\">用户中心</a><a href=\"http://passport.we54.com/index/we54vip\" target=\"_blank\" style=\" color:#ff7f00;\">申请认证</a><a href=\"http://bbs.we54.com/pm.php\" target=\"_blank\" style=\" height:18px; margin:8px 13px 0 0; padding:3px 0 0 13px; border-left:#d5d5d5 1px solid; color:#0035a0;\">短消息</a><a href=\"http://bbs.we54.com/memcp.php\" target=\"_blank\" style=\" height:18px; margin:8px 13px 0 0; padding:3px 0 0 13px; border-left:#d5d5d5 1px solid; color:#0035a0;\">您好！".$_SESSION["Zend_Auth"]['storage']->nickname." </a><span><em id=\"all_channel_header_name\">栏目导航</em><b id=\"all_channel_header_box\" style=\"display:none;\"></b><i id=\"all_channel_header_mainbav\" style=\"display:none;\"><ul><li><pre><a href=\"http://news.we54.com/\">大连你好</a></pre><pre><a href=\"http://blog.we54.com/\">博客</a></pre><pre><a href=\"http://bbs.we54.com/\">社区</a></pre><pre><a href=\"http://54class.we54.com/\">五年四班</a></pre><pre><a href=\"http://pic.we54.com/\">图片</a></pre></li><li><pre><a href=\"http://moda.we54.com/\" style=\" color:#f31e82;\">美达</a></pre><pre><a href=\"http://lichi.we54.com/\" style=\" color:#1070ba;\">荔枝先生</a></pre></li><li><pre><a href=\"http://news.we54.com/\">地产</a></pre><pre><a href=\"http://blog.we54.com/\">汽车</a></pre><pre><a href=\"http://bbs.we54.com/\">旅游</a></pre><pre><a href=\"http://pub.we54.com/\">夜店</a></pre><pre><a href=\"http://pic.we54.com/\">财经</a></pre><pre><a href=\"http://pic.we54.com/\">教育</a></pre><pre><a href=\"http://pic.we54.com/\">餐饮</a></pre></li></ul></i></span><a href=\"http://www.we54.com/\" style=\" font-weight:bold; color:#666666;\">新青年网首页</a></dd>')";
             }else	{ 
							
					echo "document.write('<dt><a href=\"#\" target=\"_blank\" style=\" height:18px; margin:8px 0 0 13px; padding:3px 0 0 13px; border-left:#d5d5d5 1px solid;\">帮助</a><em>]</em><a href=\"http://passport.we54.com/Index/register\">免费注册</a><em>[</em><i>或</i><em>]</em><a href=\"http://passport.we54.com/Index/login?forward=".$_GET['forward']."\">登录</a><em>[</em><i>您好！欢迎来到新青年网论坛  请</i><span><em id=\"all_channel_header_name\">栏目导航</em><b id=\"all_channel_header_box\" style=\"display:none;\"></b><i id=\"all_channel_header_mainbav\" style=\"display:none;\"><ul><li><pre><a href=\"http://news.we54.com/\">大连你好</a></pre><pre><a href=\"http://blog.we54.com/\">博客</a></pre><pre><a href=\"http://bbs.we54.com/\">社区</a></pre><pre><a href=\"http://54class.we54.com/\">五年四班</a></pre><pre><a href=\"http://pic.we54.com/\">图片</a></pre></li><li><pre><a href=\"http://moda.we54.com/\" style=\" color:#f31e82;\">美达</a></pre><pre><a href=\"http://lichi.we54.com/\" style=\" color:#1070ba;\">荔枝先生</a></pre></li><li><pre><a href=\"http://house.we54.com/\">地产</a></pre><pre><a href=\"http://www.we54.com/\">汽车</a></pre><pre><a href=\"http://www.we54.com/\">旅游</a></pre><pre><a href=\"http://www.we54.com/\">夜店</a></pre><pre><a href=\"http://www.we54.com/\">财经</a></pre><pre><a href=\"http://www.we54.com/\">教育</a></pre><pre><a href=\"http://www.we54.com/\">餐饮</a></pre></li></ul></i></span><a href=\"http://www.we54.com/\" style=\" margin:11px 13px 0 0; font-weight:bold; color:#666666;\">新青年网首页</a></dt>')";
 					}                          
?>